### ISSUE TITLE
Stereo Rectification

### ISSUE THREAD

**Issue by suhas1999** [Wenzhengchina/Matching-in-the-Dark#1]
Hi!
Thanks for making this dataset open-source which has amazing utility in real-world applications. Is it possible to give the code for rectification of these images? or  intrinsic parameters matrices or stereo camera calibration checkerboard images?

**Comment by Wenzhengchina** [comment]
Thank you for your question! Actually, we used the Matlab toolbox to calibrate the camera. (based on the method of Zhang et al.) I can provide the intrinsic parameters. 

The original image size is (6744,4502)
focallength_x = 4.504986436499113e+03
focallength_y = 4.513311442889859e+03
x0 = 3.363322177533149e+03
y0 = 2.291824660547715e+03
distCoeffs = (-0.117918271740560, 0.075246403574314, 0, 0)

**Comment by suhas1999** [comment]
Thanks for the quick reply!
1. I see you gave the intrinsic parameters can you also provide extrinsic parameters(R,T which represents transformation from pixel coordinates to world coordinates)?
2. Since it is a stereo system can I get the parameters of the second camera too?
3. Also is it possible to save the camera params objs which obtained from calibration as file and send? Or checkerboard images where I can run calibration myself?

**Comment by Wenzhengchina** [comment]
1. We provided ground truth of R and T with .npy files. (see folder GT_Correspondence)
2. We only use one camera for data collection.
3. I will put checkerboard images on the google drive, that you can download it.

**Comment by suhas1999** [comment]
In 1.) The R and T provided are between the two views of the stereo pair. When single-camera calibration is done there is a projective matrix that has R and T?
2.) ok
3.) Thanks! Will look forward to checkerboard images

**Comment by suhas1999** [comment]
Hi @Wenzhengchina,

Just a small reminder. Did you upload the checkerboard images? If yes, can you send the link to the folder?

**Comment by suhas1999** [comment]
Hi @Wenzhengchina 
Thanks for uploading the checkerboard images. Can u also provide the code used for getting the ground truth E,R,T matrices?

**Comment by Wenzhengchina** [comment]
Sorry for the late reply. I think you can get the estimated E (R, T can be got from the decomposition of E) using RootSIFT + NG-RANSC with the ground truth RGB images first.  Then you can perform the manual inspection as mentioned in our paper.
