### ISSUE TITLE
Is it possible to get ground truth fundamental matrix?

### ISSUE THREAD

**Issue by junyongjeon** [Wenzhengchina/Matching-in-the-Dark#2]
hi, is it possible to get ground truth fundamental matrix for every dataset sequence?
thank you.

**Comment by suhas1999** [comment]
![image](https://user-images.githubusercontent.com/45829229/176897251-de74019c-a79f-42ea-9cb1-802346599166.png)

similar to this I think we can do this using 8 point fundamental algorithms estimation method

**Comment by Wenzhengchina** [comment]
Yes, as commented above, we can use the given essential matrix and K (Intrinsic matrix). See [https://cs.stackexchange.com/questions/41327/what-is-the-difference-between-the-fundamental-matrix-and-the-essential-matrix](here)
